### ISSUE TITLE
InilineParamEncoder:  failing after 20 arguments

### ISSUE THREAD

**Issue by jerryclinesmith** [discourse/mini_sql#41]
The logic is partially matching arguments, so if you have 2 keys that start with the same string it encodes incorrectly.

Sample test:
```
def test_duplicate_arg_encoding
  result = @encoder.encode("select :arg2, :arg20", arg2: 1, arg20: 2)
  assert_equal("select 1, 2", result)
end
```

Results:
```
MiniSql::TestInlineParamEncoder#test_duplicate_arg_encoding [inline_param_encoder_test.rb:20]:
Expected: "select 1, 2"
  Actual: "select 1, 10"
```

**Comment by SamSaffron** [comment]
Thanks Jerry, just pushed a fix!

**Comment by evgenybron** [comment]
@SamSaffron 
Hey, can you please release a version with this fix.
Thanks;

**Comment by SamSaffron** [comment]
yikes this is old... doing a release right now!

**Comment by SamSaffron** [comment]
@evgenybron I started looking at this today and can not do a release until ci passes nicely... made a few fixes here: https://github.com/discourse/mini_sql/pull/44 

But more remain, we have a flake on 3.0, ci is failing due to a bug in rubocop on 3.1. PR to fix this totally welcome.

**Comment by evgenybron** [comment]
thanks @SamSaffron  🎉
